name: local
payments:
  base_url: http://127.0.0.1:3000
notifications:
  base_url: http://127.0.0.1:3000
connections:
  payments_api:
    execution_library: http
    lifecycle: ephemeral
    http:
      request:
        fields:
          base_url: http://127.0.0.1:3000
        headers:
          Authorization: Bearer {{ os-env-var:PAYMENTS_TOKEN }}
